model_params:
  logistic_regression:
    C: [0.001, 0.01, 0.1, 1, 10, 100]
    penalty: ["l1", "l2", "elasticnet"]
    solver: ["liblinear", "saga"]
    l1_ratio: [0.1, 0.5, 0.9]
    max_iter: [2000]

  random_forest:
    n_estimators: [100, 200, 300, 500]
    max_depth: [10, 20, 30, ~]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1,2,4]
    class_weight: ["balanced", ~]
    n_jobs: [-1]

  svm:
    C: [0.1, 1, 10, 100]
    kernel: ["rbf", "linear"]
    gamma: ["scale", "auto", 0.01, 0.1]
    class_weight: ["balanced", ~]
    probability: [true]   # required for ROC AUC