artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/armandoalbornoz/datasets/raw/3b467afbb564121d68167bcb93dc3ba474531bfa/archive(1).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion